### ISSUE TITLE
npm start Issue 

### ISSUE THREAD

**Issue by ksummersill** [Squarefront/squarespace-template-helper#18]
Attached are the directions that i followed between your videos and the instructions. I am also attached the debug file. I recieive the error when i run a npm start; can you please help with the issue. 

1. Install Node Full @ nodejs.org
I originally download the LTS version and the install failed. I needed to run a npm clear cache to remove all old information from install. I then ran the full install path. 

Download the Square Space Server
npm install -g @squarespace/squarespace-server

Make sure git is installed. You can download get at https://git-scm.com/
Now that git is installed you can make a clone base template. I recommend using a square front template. 

git clone git@github.com:Squarefront/squarespace-template-helper.git yourprojectname

https://github.com/Squarefront/squarespace-template-helper.git

Note sure what the difference is except for the bottom link gave me all the files I needed. 

You change the yourprojectname and the location where you want the template to be developmental @; your choice. 

Next; to make sure you have all the dependence; make sure to use the command npm I . This will pull all the node_module folder items. Js Hobo is also used to make sure we can code JQuery. JS hobo is a breakdown version of JQuery. Think of it as a small distribution package.  

Next run the command npm start 

*I receive this error message:

    at expr_atom (eval at <anonymous> (C:\Dev\BasicTemplate\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2615:24)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! squarespace-template-helper@0.3.0 watch: `webpack -d --watch --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the squarespace-template-helper@0.3.0 watch script 'webpack -d --watch --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the squarespace-template-helper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -d --watch --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs squarespace-template-helper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls squarespace-template-helper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\BasicTemplate\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! squarespace-template-helper@0.3.0 start: `npm run watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the squarespace-template-helper@0.3.0 start script 'npm run watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the squarespace-template-helper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs squarespace-template-helper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls squarespace-template-helper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\BasicTemplate\npm-debug.log

Here is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle squarespace-template-helper@0.3.0~prestart: squarespace-template-helper@0.3.0
6 silly lifecycle squarespace-template-helper@0.3.0~prestart: no script for prestart, continuing
7 info lifecycle squarespace-template-helper@0.3.0~start: squarespace-template-helper@0.3.0
8 verbose lifecycle squarespace-template-helper@0.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle squarespace-template-helper@0.3.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Dev\BasicTemplate\node_modules\.bin;C:\Program Files\nodejs;C:\Users\ksumm_000\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\ksumm_000\bin;C:\app\SumTech\product\11.2.0\client_2;C:\app\SumTech\product\11.2.0\client_2\bin;C:\app\SumTech\product\11.2.0\client_1;C:\app\SumTech\product\11.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Ruby23-x64\bin;C:\Users\ksumm_000\AppData\Local\Microsoft\WindowsApps;C:\Users\ksumm_000\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle squarespace-template-helper@0.3.0~start: CWD: C:\Dev\BasicTemplate
11 silly lifecycle squarespace-template-helper@0.3.0~start: Args: [ '/d /s /c', 'npm run watch' ]
12 silly lifecycle squarespace-template-helper@0.3.0~start: Returned: code: 1  signal: null
13 info lifecycle squarespace-template-helper@0.3.0~start: Failed to exec start script
14 verbose stack Error: squarespace-template-helper@0.3.0 start: `npm run watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid squarespace-template-helper@0.3.0
16 verbose cwd C:\Dev\BasicTemplate
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error squarespace-template-helper@0.3.0 start: `npm run watch`
22 error Exit status 1
23 error Failed at the squarespace-template-helper@0.3.0 start script 'npm run watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the squarespace-template-helper package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs squarespace-template-helper
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls squarespace-template-helper
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mwickett** [comment]
Did `npm i` run without errors?

**Comment by ksummersill** [comment]
Yes it did

**Comment by ksummersill** [comment]
I recieved all the modules, I will run through the step again and double check

**Comment by ksummersill** [comment]
Yes i did receive an error running the npm command. 


ERROR in ./dist/hobo.build.js
Module parse failed: C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\dist\hobo.build.js Unexpected token (46:19)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (46:19)
    at Parser.pp$4.raise (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseIdent (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:2189:1
2)
    at Parser.pp$3.parseSubscripts (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
728:32)
    at Parser.pp$3.parseExprSubscripts (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.
js:1718:17)
    at Parser.pp$3.parseMaybeUnary (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
692:19)
    at Parser.pp$3.parseExprOps (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1637
:21)
    at Parser.pp$3.parseMaybeConditional (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acor
n.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:
1597:21)
    at Parser.pp$3.parseExpression (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
573:21)
    at Parser.pp$1.parseStatement (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:72
7:47)
    at Parser.pp$1.parseBlock (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:981:25
)
    at Parser.pp$3.parseFunctionBody (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js
:2105:24)
    at Parser.pp$1.parseFunction (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:106
5:10)
    at Parser.pp$3.parseExprAtom (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:181
0:19)
    at Parser.pp$3.parseExprSubscripts (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.
js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
692:19)
    at Parser.pp$3.parseExprOps (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1637
:21)
    at Parser.pp$3.parseMaybeConditional (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acor
n.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:
1597:21)
    at Parser.pp$3.parseExprList (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:216
5:22)
    at Parser.pp$3.parseSubscripts (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
741:35)
    at Parser.pp$3.parseExprSubscripts (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.
js:1718:17)
    at Parser.pp$3.parseMaybeUnary (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
692:19)
    at Parser.pp$3.parseExprOps (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1637
:21)
    at Parser.pp$3.parseMaybeConditional (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acor
n.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:
1597:21)
    at Parser.pp$3.parseExpression (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:1
573:21)
    at Parser.pp$1.parseStatement (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:72
7:47)
    at Parser.pp$1.parseTopLevel (C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\node_modules\acorn\dist\acorn.js:638
:25)
'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build" "--" "'attr" "eq" "not" "detach" "append" "prepend" "remove" "parent" "filter'"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! properjs-hobo@0.3.10 postbuild: `webpack dist/hobo.build.js dist/hobo.build.dist.js && ./node_modules/.bin/webp
ack hobo.js dist/hobo.dist.js && npm run min && npm run doc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the properjs-hobo@0.3.10 postbuild script 'webpack dist/hobo.build.js dist/hobo.build.dist.js && ./no
de_modules/.bin/webpack hobo.js dist/hobo.dist.js && npm run min && npm run doc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the properjs-hobo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack dist/hobo.build.js dist/hobo.build.dist.js && ./node_modules/.bin/webpack hobo.js dist/hobo.dist.js
 && npm run min && npm run doc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs properjs-hobo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls properjs-hobo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\SquareSpaceTemp\node_modules\properjs-hobo\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! squarespace-template-helper@0.3.0 postinstall: `cd ./node_modules/properjs-hobo && npm install && npm run build
 -- 'attr eq not detach append prepend remove parent filter'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the squarespace-template-helper@0.3.0 postinstall script 'cd ./node_modules/properjs-hobo && npm inst
all && npm run build -- 'attr eq not detach append prepend remove parent filter''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the squarespace-template-helper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./node_modules/properjs-hobo && npm install && npm run build -- 'attr eq not detach append prepend remov
e parent filter'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs squarespace-template-helper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls squarespace-template-helper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\SquareSpaceTemp\npm-debug.log
PS C:\Dev\SquareSpaceTemp>

**Comment by ksummersill** [comment]
The error is more related to the hobo. Can hobo install on Windows 10?

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN properjs-hobo@0.3.3 No license field.

> properjs-hobo@0.3.3 build C:\Dev\templatehelper\node_modules\properjs-hobo
> node build.js "'attr" "eq" "not" "detach" "append" "prepend" "remove" "parent" "filter'"

> [Hobo] Generated custom build with -- 'attr

> properjs-hobo@0.3.3 postbuild C:\Dev\templatehelper\node_modules\properjs-hobo
> webpack dist/hobo.build.js dist/hobo.build.dist.js && webpack hobo.js dist/hobo.dist.js && npm run min && npm run doc

Hash: 8f371a4d9917b1a128b6
Version: webpack 1.13.2
Time: 147ms
    + 1 hidden modules

ERROR in ./dist/hobo.build.js
Module parse failed: C:\Dev\templatehelper\node_modules\properjs-hobo\dist\hobo.build.js Unexpected token (46:19)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (46:19)

**Comment by mwickett** [comment]
What version of Node are you running?

**Comment by ksummersill** [comment]
v6.7.0

**Comment by GabrielBuragev** [comment]
having the same issue :)

**Comment by jasonbarone** [comment]
Sorry, late on responding here. I'm refactoring the entire project to update it to latest tech. That should solve many of the issues.

**Comment by user905** [comment]
Any update here? @jasonbarone 
Am having this issue, and finding it not uncommon on the boards.
